import { useState } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import SectionHeading from '@/components/SectionHeading';
import { learningRecords } from '@/data/certifications';

export default function Certifications() {
  const [showAll, setShowAll] = useState(false);
  const reduceMotion = useReducedMotion();
  const categories = Array.from(new Set(learningRecords.map((record) => record.category)));
  const visibleRecords = showAll ? learningRecords : learningRecords.slice(0, 4);
  return <section id="certifications" className="scroll-mt-20 py-20 sm:py-28" aria-labelledby="certifications-title"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Certifications / learning" title="Training records and learning badges." description="Learning achievements are grouped by topic and presented with their provider context." /><p id="certifications-title" className="sr-only">Certifications and learning records</p><div className="mt-10 space-y-8">{categories.map((category) => { const records = visibleRecords.filter((record) => record.category === category); if (records.length === 0) return null; return <div key={category}><h3 className="font-mono text-xs font-semibold uppercase tracking-[0.19em] text-emerald-200">{category}</h3><motion.div layout={!reduceMotion} className="mt-3 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><AnimatePresence mode="popLayout">{records.map((record) => <motion.article key={record.title} layout={!reduceMotion} initial={reduceMotion ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={reduceMotion ? undefined : { opacity: 0, y: -12 }} className="flex flex-col rounded-xl border border-white/10 bg-white/[0.025] p-5"><p className="font-mono text-[0.65rem] uppercase tracking-[0.14em] text-cyan-300">{record.provider}</p><h4 className="mt-3 text-base font-semibold leading-6 text-white">{record.title}</h4><p className="mt-2 text-xs text-slate-500">{record.kind}</p><div className="mt-4 flex flex-wrap gap-2">{record.topics.map((topic) => <span key={topic} className="rounded-md border border-white/10 px-2 py-1 text-xs text-slate-300">{topic}</span>)}</div>{record.url && <a href={record.url} target="_blank" rel="noreferrer" className="mt-auto pt-5 text-sm font-semibold text-cyan-200 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">View certificate ↗<span className="sr-only"> (opens in a new tab)</span></a>}</motion.article>)}</AnimatePresence></motion.div></div>; })}</div><div className="mt-8 flex justify-center"><button type="button" onClick={() => setShowAll((current) => !current)} className="rounded-md border border-cyan-300/35 px-4 py-2.5 text-sm font-semibold text-cyan-100 transition hover:bg-cyan-300/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">{showAll ? 'Show Less' : 'View All Certifications'}</button></div></div></section>;
}
