import Link from 'next/link';
import FlowSteps from '@/components/FlowSteps';
import SectionHeading from '@/components/SectionHeading';
import { forensicsSteps, iamSteps, socSteps } from '@/data/content';
import { projects } from '@/data/projects';

const tags = (items: string[]) => <div className="mt-6 flex flex-wrap gap-2">{items.map((item) => <span key={item} className="rounded-md border border-white/10 bg-black/20 px-2.5 py-1 text-xs text-slate-300">{item}</span>)}</div>;

export function SOCJourney() {
  return <section id="soc" className="scroll-mt-20 border-y border-white/10 bg-white/[0.015] py-20 sm:py-28" aria-labelledby="soc-title"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><SectionHeading eyebrow="SOC analyst journey" title="A workflow for building SOC-oriented skills." /><p id="soc-title" className="mt-5 leading-7 text-slate-400">As a SOC Analyst Candidate, I am building a structured understanding of how defenders collect context, monitor activity, investigate signals and document lessons learned.</p>{tags(['Network Security', 'Log Analysis', 'SOC', 'Incident Response', 'Cyber Threat Intelligence', 'Security Awareness'])}</div><div className="rounded-xl border border-cyan-300/20 bg-[#08111b] p-5 sm:p-7"><p className="mb-5 font-mono text-xs uppercase tracking-[0.18em] text-cyan-300">Defensive workflow</p><FlowSteps steps={socSteps} label="SOC analyst learning workflow" /></div></div></section>;
}

export function DigitalForensics() {
  const project = projects.find((item) => item.slug === 'digital-forensics-framework');
  if (!project) return null;
  return <section id="forensics" className="scroll-mt-20 py-20 sm:py-28" aria-labelledby="forensics-title"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[1.1fr_0.9fr] lg:px-8"><div><SectionHeading eyebrow="Digital forensics" title="Digital Forensics Framework" description="A project-led view of evidence handling and documentation." /><p id="forensics-title" className="mt-5 text-sm leading-7 text-slate-400">The public repository describes case registration, evidence logging, MD5/SHA-256 hashing, chain-of-custody tracking and reporting in a Windows-friendly Python workflow.</p><div className="mt-7 rounded-xl border border-emerald-300/20 bg-emerald-300/[0.025] p-5 sm:p-6"><p className="mb-5 font-mono text-xs uppercase tracking-[0.18em] text-emerald-200">Evidence workflow</p><FlowSteps steps={forensicsSteps} label="Digital forensics evidence workflow" accent="green" /></div></div><aside className="rounded-xl border border-white/10 bg-white/[0.025] p-6"><p className="font-mono text-xs uppercase tracking-[0.17em] text-cyan-300">Repository capabilities</p><ul className="mt-5 space-y-3 text-sm text-slate-300">{project.highlights.map((item) => <li key={item} className="flex gap-3"><span className="text-emerald-300">✓</span><span>{item}</span></li>)}</ul><div className="mt-8 flex flex-wrap gap-4"><Link href={`/projects/${project.slug}`} className="text-sm font-semibold text-cyan-200 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">View Project →</Link><a href={project.github} target="_blank" rel="noreferrer" className="text-sm font-semibold text-slate-300 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">GitHub ↗</a></div></aside></div></section>;
}

export function AISecurity() {
  return <section id="ai-security" className="scroll-mt-20 border-y border-white/10 bg-white/[0.015] py-20 sm:py-28" aria-labelledby="ai-security-title"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><SectionHeading eyebrow="AI × cybersecurity" title="AI learning connected to practical systems." /><p id="ai-security-title" className="mt-5 leading-7 text-slate-400">AI is a secondary focus that supports security learning. The N-ONE repository provides a concrete computer-vision project reference; learning records include IBM AI Fundamentals and Google Cloud AI learning.</p><div className="mt-7"><Link href="#projects" className="inline-flex rounded-md border border-cyan-300/35 px-4 py-2.5 text-sm font-semibold text-cyan-100 transition hover:bg-cyan-300/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">Explore Projects →</Link></div></div><div className="grid gap-3 sm:grid-cols-2">{['Artificial Intelligence', 'Machine Learning', 'Deep Learning', 'Computer Vision', 'NLP', 'Neural Networks', 'Generative AI', 'Prompt Engineering', 'Responsible AI'].map((item, index) => <div key={item} className={`rounded-lg border p-4 ${index === 3 ? 'border-cyan-300/35 bg-cyan-300/[0.06]' : 'border-white/10 bg-black/10'}`}><span className="font-mono text-[0.63rem] tracking-[0.14em] text-slate-500">AI / {String(index + 1).padStart(2, '0')}</span><p className="mt-2 text-sm font-medium text-slate-200">{item}</p></div>)}</div></div></section>;
}

export function CloudSecurity() {
  return <section id="cloud" className="scroll-mt-20 py-20 sm:py-28" aria-labelledby="cloud-title"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[1.1fr_0.9fr] lg:px-8"><div><SectionHeading eyebrow="Cloud security & operations" title="Cloud learning through a security lens." /><p id="cloud-title" className="mt-5 leading-7 text-slate-400">Google Cloud learning records are represented as training and badges. They demonstrate learning topics, not professional cloud-engineering experience.</p>{tags(['Cloud Security', 'IAM', 'Network Security', 'Data Protection', 'Cloud Monitoring', 'Logging', 'Observability', 'Reliability', 'Cloud Infrastructure', 'Cloud Modernization'])}</div><div className="rounded-xl border border-cyan-300/20 bg-[#08111b] p-6"><p className="font-mono text-xs uppercase tracking-[0.18em] text-cyan-300">Cloud operations model</p><div className="mt-6 space-y-3">{[['Protect', 'IAM · network controls · data protection'], ['Observe', 'Monitoring · logging · observability'], ['Improve', 'Reliability · modernization · learning']].map(([title, text], index) => <div key={title} className="flex gap-4 rounded-lg border border-white/10 bg-white/[0.02] p-4"><span className="font-mono text-sm text-emerald-300">0{index + 1}</span><div><p className="text-sm font-semibold text-white">{title}</p><p className="mt-1 text-sm text-slate-400">{text}</p></div></div>)}</div></div></div></section>;
}

export function IAM() {
  return <section id="iam" className="scroll-mt-20 border-y border-white/10 bg-white/[0.015] py-20 sm:py-28" aria-labelledby="iam-title"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Identity & access management" title="Identity is a security control plane." description="Learning emphasis includes identity management, authentication, authorization and access control." /><div className="mt-10 rounded-xl border border-cyan-300/20 bg-[#08111b] p-5 sm:p-7"><FlowSteps steps={iamSteps} label="Identity and access management flow" /><div className="mt-7 grid gap-3 border-t border-white/10 pt-6 sm:grid-cols-2 lg:grid-cols-4">{['IAM', 'Identity Management Assessment', 'Identity Management Design', 'Access Control'].map((item) => <div key={item} className="rounded-lg border border-white/10 bg-white/[0.025] p-4 text-sm text-slate-200">{item}</div>)}</div></div><p id="iam-title" className="mt-5 text-sm leading-7 text-slate-400">Learning evidence: Tata Cybersecurity Analyst Job Simulation and Google Cloud Trust and Security learning.</p></div></section>;
}
