import Link from 'next/link';
import SectionHeading from '@/components/SectionHeading';
import { skillCategories, skillEvidence } from '@/data/skills';

function ExternalOrInternalLink({ href, children }: { href: string; children: React.ReactNode }) {
  const external = href.startsWith('http');
  return external ? <a href={href} target="_blank" rel="noreferrer" className="rounded-sm text-xs text-cyan-200 underline decoration-cyan-300/30 underline-offset-4 transition hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">{children}<span className="sr-only"> (opens in a new tab)</span></a> : <Link href={href} className="rounded-sm text-xs text-cyan-200 underline decoration-cyan-300/30 underline-offset-4 transition hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">{children}</Link>;
}

export default function SkillsSection() {
  return <section id="skills" className="scroll-mt-20 py-20 sm:py-28" aria-labelledby="skills-title"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Technical skills" title="Learning areas, not percentage bars." description="These categories organize coursework, learning records and projects. Individual evidence is shown for key focus areas." /><p id="skills-title" className="sr-only">Technical skills</p><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{skillCategories.map((category) => <article key={category.name} className="rounded-xl border border-white/10 bg-white/[0.025] p-5"><h3 className="font-mono text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300">{category.name}</h3><div className="mt-4 flex flex-wrap gap-2">{category.skills.map((skill) => <span key={skill} className="rounded-md border border-white/10 bg-black/20 px-2.5 py-1.5 text-xs text-slate-300">{skill}</span>)}</div></article>)}</div><div className="mt-10 grid gap-4 lg:grid-cols-2">{skillEvidence.map((item) => <article key={item.skill} className="rounded-xl border border-cyan-300/20 bg-cyan-300/[0.025] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-lg font-semibold text-white">{item.skill}</h3><span className="rounded border border-emerald-300/25 px-2 py-1 font-mono text-[0.62rem] uppercase tracking-[0.1em] text-emerald-200">{item.level}</span></div><p className="mt-2 font-mono text-[0.65rem] uppercase tracking-[0.15em] text-slate-500">Evidence</p><ul className="mt-3 space-y-2">{item.evidence.map((evidence) => <li key={evidence.label}><ExternalOrInternalLink href={evidence.link}>{evidence.label}</ExternalOrInternalLink></li>)}</ul></article>)}</div></div></section>;
}